Boshen/cargo-shear

README.md, src/lib.rs
We can ignore crates like this
```toml
[package.metadata.cargo-shear]
ignored = ["crate"]
```
=> feat: support for ignore dependencies

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 0.0.10 -> 0.0.11 (✓ API compatible changes)
<blockquote>
- add release-plz
- add typos
- add `cargo publish`
</blockquote>
</p></details>
---
=> chore: release v0.0.11

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 0.0.13 -> 0.0.14 (✓ API compatible changes)
<blockquote>
- fix release-binaries
</blockquote>
</p></details>
---
=> chore: release v0.0.14

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 0.0.14 -> 0.0.15 (✓ API compatible changes)
<blockquote>
- fix release
</blockquote>
</p></details>
---
=> chore: release v0.0.15

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 0.0.15 -> 0.0.16 (✓ API compatible changes)
<blockquote>
- better output messages
- update README about ignoring false positives
- update README
- update README
</blockquote>
</p></details>
---
=> chore: release v0.0.16

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 0.0.16 -> 0.0.17 (✓ API compatible changes)
<blockquote>
- ignored packages by package name instead of normalized name
- fix broken ci
- make `shear_package` the more readable
- minor tweak
- add `--no-deps` to `cargo metadata`
- add `just ready`
- run shear on this repo
</blockquote>
</p></details>
---
=> chore: release v0.0.17

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 0.0.17 -> 0.0.18 (⚠️ API breaking changes)
```
--- failure struct_missing: pub struct removed or renamed ---
Description:
A publicly-visible struct cannot be imported by its prior path. A `pub use` may have been removed, or the struct itself may have been renamed or removed entirely.
ref: https://doc.rust-lang.org/cargo/reference/semver.html#item-remove
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.30.0/src/lints/struct_missing.ron
Failed in:
struct cargo_shear::Error, previously in file /tmp/.tmpGYRpOu/cargo-shear/src/lib.rs:21
```
<blockquote>
- use cargo metadata module resolution to get module names instead of package names
- add `profile.release` to Cargo.toml
- small tweaks
</blockquote> …
=> chore: release v0.0.18

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 0.0.18 -> 0.0.19 (✓ API compatible changes)
<blockquote>
- use `--all-features` to get all deps
- update README
</blockquote>
</p></details>
---
=> chore: release v0.0.19

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 0.0.20 -> 0.0.21 (✓ API compatible changes)
<blockquote>
- fix github.ref read
</blockquote>
</p></details>
---
=> chore: release v0.0.21

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 0.0.21 -> 0.0.22 (✓ API compatible changes)
<blockquote>
- rust v1.77.0 has a different package id representation
</blockquote>
</p></details>
---
=> chore: release v0.0.22

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 0.0.22 -> 0.0.23 (✓ API compatible changes)
<blockquote>
- collect import from all use declarations
- use [lints.clippy]
</blockquote>
</p></details>
---
=> chore: release v0.0.23

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 0.0.23 -> 0.0.24 (✓ API compatible changes)
<blockquote>
- handle package rename in workspace dependencies
- add ignore with [workspace.metadata.cargo-shear]
- space out printing
</blockquote>
</p></details>
---
=> chore: release v0.0.24

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 0.0.24 -> 0.0.25 (✓ API compatible changes)
<blockquote>
- *(deps)* update dependency rust to v1.78.0 ([#40](https://github.com/Boshen/cargo-shear/pull/40))
- *(renovate)* add rust-toolchain
- *(deps)* update rust crate cargo-util-schemas to 0.3.0 ([#39](https://github.com/Boshen/cargo-shear/pull/39))
- *(deps)* update rust crates ([#38](https://github.com/Boshen/cargo-shear/pull/38))
- *(deps)* update rust crate bpaf to 0.9.12 ([#37](https://github.com/Boshen/cargo-shear/pull/37))
- *(deps)* update rust crate cargo_toml to 0.20.2 ([#36](https://github.com/Boshen/cargo-shear/pull/36))
- *(deps)* update rust crate cargo_toml to 0.20.1 ([#35](https://github.com/Boshen/cargo-shear/pull/35))
- *(deps)* update rust crates …
=> chore: release v0.0.25

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 0.0.25 -> 0.0.26
<blockquote>
- exit code is 0 when performing fix ([#52](https://github.com/Boshen/cargo-shear/pull/52))
- *(deps)* lock file maintenance rust crates ([#49](https://github.com/Boshen/cargo-shear/pull/49))
- update README
- update README
- link prior arts
- document prior arts
- allow branch `renovate/**`
- *(deps)* lock file maintenance rust crates ([#46](https://github.com/Boshen/cargo-shear/pull/46))
- *(deps)* lock file maintenance rust crates ([#44](https://github.com/Boshen/cargo-shear/pull/44))
- add PR from astral-sh/uv
- *(deps)* lock file maintenance rust crates ([#43](https://github.com/Boshen/cargo-shear/pull/43))
- use shared renovate config
</blockquote>
</p></details>
---
This PR was …
=> chore: release v0.0.26

src/lib.rs
It seems like workspace ignored deps were not being handled correctly - they should be appended to package-level deps.
=> feat: inherit package level ignore from workspace level ignore

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.1.2 -> 1.1.3 (✓ API compatible changes)
<blockquote>
- search for tokens in `Verbatim` which are not interpreted by syn. ([#87](https://github.com/Boshen/cargo-shear/pull/87))
- *(renovate)* bump versions
- *(deps)* update rust crates ([#86](https://github.com/Boshen/cargo-shear/pull/86))
- *(deps)* update rust crates ([#84](https://github.com/Boshen/cargo-shear/pull/84))
- *(deps)* update dependency rust to v1.81.0 ([#83](https://github.com/Boshen/cargo-shear/pull/83))
- *(deps)* update dependency rust to v1.80.1 ([#82](https://github.com/Boshen/cargo-shear/pull/82))
- Update README.md
- Add trophy cases for reqsign ([#80](https://github.com/Boshen/cargo-shear/pull/80))
- *(deps)* update rust crates …
=> chore: release v1.1.3

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.1.3 -> 1.1.4 (✓ API compatible changes)
<blockquote>
- *(deps)* update rust crates ([#99](https://github.com/Boshen/cargo-shear/pull/99))
- *(deps)* update rust crate serde_json to 1.0.133 ([#98](https://github.com/Boshen/cargo-shear/pull/98))
- *(deps)* update rust crate anyhow to 1.0.93 ([#97](https://github.com/Boshen/cargo-shear/pull/97))
- *(deps)* update rust crates ([#96](https://github.com/Boshen/cargo-shear/pull/96))
- *(deps)* update rust crates ([#94](https://github.com/Boshen/cargo-shear/pull/94))
- *(deps)* update rust crates ([#92](https://github.com/Boshen/cargo-shear/pull/92))
- *(deps)* update dependency rust to v1.82.0 ([#91](https://github.com/Boshen/cargo-shear/pull/91))
- *(deps)* update rust …
=> chore: release v1.1.4

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.1.6 -> 1.1.7 (✓ API compatible changes)
<blockquote>
- update rustfmt
</blockquote>
</p></details>
---
=> chore: release v1.1.7

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.1.7 -> 1.1.8 (✓ API compatible changes)
<blockquote>
- macos-12 (deprecated) -> macos-13
</blockquote>
</p></details>
---
=> chore: release v1.1.8

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.1.8 -> 1.1.9 (✓ API compatible changes)
<blockquote>
- persist-credentials: true
- change token
- persist-credentials: false
- *(deps)* pin dependencies (#120)
- add components
- fix overly broad permissions
- update
- add zizmor
- update justfile
- update renovate.json
- *(deps)* lock file maintenance rust crates (#118)
- Update README.md
- *(deps)* update rust crates (#116)
- *(deps)* update dependency rust to v1.84.1 (#115)
- *(deps)* update rust crate bpaf to 0.9.16 (#114)
- *(deps)* update rust crate serde_json to 1.0.137 (#113)
- *(deps)* update rust crate serde_json to 1.0.136 (#112)
- *(deps)* update rust crates (#110)
</blockquote>
</p></details>
---
This PR was generated with …
=> chore: release v1.1.9

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.1.9 -> 1.1.10 (✓ API compatible changes)
<blockquote>
- Rust 2024
- *(deps)* update dependency rust to v1.85.0 (#126)
- *(deps)* update taiki-e/install-action action to v2.48.15 (#125)
- *(deps)* update taiki-e/install-action action to v2.48.14 (#124)
- *(deps)* update github-actions (#123)
- use oxc-project/setup-rust
- pinGitHubActionDigestsToSemver
</blockquote>
</p></details>
---
=> chore: release v1.1.10

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.1.11 -> 1.1.12 (✓ API compatible changes)
<blockquote>
- use regex-lite
- `cargo upgrade -i`
- *(deps)* update dependency rust to v1.86.0 ([#146](https://github.com/Boshen/cargo-shear/pull/146))
- *(deps)* update github-actions ([#144](https://github.com/Boshen/cargo-shear/pull/144))
- *(deps)* lock file maintenance ([#145](https://github.com/Boshen/cargo-shear/pull/145))
- *(deps)* update github-actions ([#142](https://github.com/Boshen/cargo-shear/pull/142))
- *(deps)* update dependency rust to v1.85.1 ([#140](https://github.com/Boshen/cargo-shear/pull/140))
</blockquote>
</p></details>
---
=> chore: release v1.1.12

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.1.13 -> 1.1.14 (✓ API compatible changes)
<blockquote>
- build on ubuntu-latest. ubuntu-20.04 is retired ([#153](https://github.com/Boshen/cargo-shear/pull/153))
</blockquote>
</p></details>
---
=> chore: release v1.1.14

src/lib.rs
As I left in the comment, it's a bit more complicated to fix features.
ex. let's say we're removing `bytes`:
```toml
[features]
bytes = []
explicit = ["dep:bytes"]
implicit = ["bytes"]
```
=> feat: `--fix` remove unused dependencies from [features] section

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.1.14 -> 1.2.0 (✓ API compatible changes)
<blockquote>
- `--fix` remove unused dependencies from [features] section ([#157](https://github.com/Boshen/cargo-shear/pull/157))
</blockquote>
</p></details>
---
=> chore: release v1.2.0

README.md, src/lib.rs, src/tests.rs
nightly only
Based on cargo expand, but not as sophisticated. This is muuuuch slower because it has to compile every target so I'm not sure if it's practical, but super neat. Running it on the mono-workspace at work and it works pretty well.
=> Add `--expand` to expand macros to find any hidden dependencies

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.2.0 -> 1.2.1 (✓ API compatible changes)
<blockquote>
- Use mimalloc on pre-built binaries. 1.2x times faster! ([#162](https://github.com/Boshen/cargo-shear/pull/162))
- Add `--expand` to expand macros to find any hidden dependencies ([#159](https://github.com/Boshen/cargo-shear/pull/159))
</blockquote>
</p></details>
---
=> chore: release v1.2.1

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.2.1 -> 1.2.2 (✓ API compatible changes)
<blockquote>
- use latest containers to build binaries
</blockquote>
</p></details>
---
=> chore: release v1.2.2

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.2.2 -> 1.2.3 (✓ API compatible changes)
<blockquote>
- pin crate-ci/typos
</blockquote>
</p></details>
---
=> chore: release v1.2.3

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.2.3 -> 1.2.4 (✓ API compatible changes)
<blockquote>
- fix windows build
</blockquote>
</p></details>
---
=> chore: release v1.2.4

README.md
~~cargo-shear hasn’t been merged into homebrew-core yet, but since there are no particular issues and it follows Homebrew’s [acceptable formulae guidelines](https://docs.brew.sh/Acceptable-Formulae), it will likely be accepted.~~
~~Assuming it will be merged, I’ve gone ahead and created a PR that updates the README in advance. Please take a look and see if the format aligns with your preferences.~~
~~Once the formula is merged, I’ll mark this PR as ready for review.~~
It's merged
```bash
brew install cargo-shear
```
- https://github.com/Homebrew/homebrew-core/pull/220832
=> README.md: Document how to install cargo-shear using homebrew

.github/workflows/release-binaries.yml, Cargo.lock, Cargo.toml, src/main.rs
Reverts #162)
fixes #170
This reverts commit da9cac9f97b44712c062682d3e14d2a4f2c309f6.
There are systems with old glibc versions.
=> Revert "perf: Use mimalloc on pre-built binaries. "

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.2.5 -> 1.2.6 (✓ API compatible changes)
<blockquote>
- use `ubuntu-22.04` instead of `ubuntu-latest` to build
- Reapply "perf: Use mimalloc on pre-built binaries. " ([#171](https://github.com/Boshen/cargo-shear/pull/171))
</blockquote>
</p></details>
---
=> chore: release v1.2.6

src/import_collector.rs, src/tests.rs
=> fix: handle whitespace in derive macro path `thiserror :: Error`

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.2.6 -> 1.2.7 (✓ API compatible changes)
<blockquote>
- handle whitespace in derive macro path `thiserror :: Error` ([#177](https://github.com/Boshen/cargo-shear/pull/177))
- *(deps)* lock file maintenance rust crates ([#179](https://github.com/Boshen/cargo-shear/pull/179))
- *(deps)* update crate-ci/typos action to v1.32.0 ([#176](https://github.com/Boshen/cargo-shear/pull/176))
- *(deps)* update crate-ci/typos action to v1.31.2 ([#174](https://github.com/Boshen/cargo-shear/pull/174))
- *(deps)* update github-actions ([#173](https://github.com/Boshen/cargo-shear/pull/173))
</blockquote>
</p></details>
---
=> chore: release v1.2.7

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.2.7 -> 1.2.8 (✓ API compatible changes)
<blockquote>
- improve ignore hint ([#188](https://github.com/Boshen/cargo-shear/pull/188))
- *(deps)* update github-actions ([#185](https://github.com/Boshen/cargo-shear/pull/185))
- *(deps)* lock file maintenance rust crates ([#186](https://github.com/Boshen/cargo-shear/pull/186))
- *(deps)* update dependency rust to v1.87.0 ([#183](https://github.com/Boshen/cargo-shear/pull/183))
- *(deps)* update github-actions ([#180](https://github.com/Boshen/cargo-shear/pull/180))
</blockquote>
</p></details>
---
=> chore: release v1.2.8

README.md, src/lib.rs
closes #147
For CI:
With `--fix`:
* 0 if found no unused dependencies so no fixes were performed,
* 1 if removed some unused dependencies. Useful for running `cargo check` after `cargo-shear` changed `Cargo.toml`.
=> feat: return exit code when `--fix`

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.2.8 -> 1.3.0 (✓ API compatible changes)
<blockquote>
- return exit code when `--fix` ([#189](https://github.com/Boshen/cargo-shear/pull/189))
</blockquote>
</p></details>
---
=> chore: release v1.3.0

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.3.0 -> 1.3.1 (✓ API compatible changes)
<blockquote>
- *(deps)* lock file maintenance rust crates ([#195](https://github.com/Boshen/cargo-shear/pull/195))
- *(deps)* update taiki-e/install-action action to v2.52.4 ([#194](https://github.com/Boshen/cargo-shear/pull/194))
- *(deps)* lock file maintenance rust crates ([#193](https://github.com/Boshen/cargo-shear/pull/193))
- *(deps)* update taiki-e/install-action action to v2.52.1 ([#192](https://github.com/Boshen/cargo-shear/pull/192))
- add fix example
</blockquote>
</p></details>
---
=> chore: release v1.3.1

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.3.1 -> 1.3.2 (✓ API compatible changes)
<blockquote>
- *(deps)* lock file maintenance rust crates ([#210](https://github.com/Boshen/cargo-shear/pull/210))
- *(deps)* update github-actions ([#209](https://github.com/Boshen/cargo-shear/pull/209))
- *(deps)* update dependency rust to v1.88.0 ([#208](https://github.com/Boshen/cargo-shear/pull/208))
- *(deps)* update taiki-e/install-action action to v2.54.0 ([#207](https://github.com/Boshen/cargo-shear/pull/207))
- *(deps)* lock file maintenance rust crates ([#205](https://github.com/Boshen/cargo-shear/pull/205))
- *(deps)* update github-actions ([#204](https://github.com/Boshen/cargo-shear/pull/204))
- *(deps)* lock file maintenance rust crates …
=> chore: release v1.3.2

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.3.2 -> 1.3.3 (✓ API compatible changes)
<blockquote>
- add file type check ([#214](https://github.com/Boshen/cargo-shear/pull/214))
- *(deps)* update crate-ci/typos action to v1.34.0 ([#212](https://github.com/Boshen/cargo-shear/pull/212))
</blockquote>
</p></details>
---
=> chore: release v1.3.3

src/lib.rs
It is said in the [`anyhow::Error` docs](https://docs.rs/anyhow/latest/anyhow/struct.Error.html#display-representations)
> The Debug format “{:?}” includes your backtrace if one was captured. Note that this is the representation you get by default if you return an error from fn main instead of printing it explicitly yourself.
Usually the `Error` is handle with `.unwrap` or other functions which finally call `panic`. And the panic handler in rust std will give a friendly tip if the backtrace is disabled. However, `cargo-shear` doesn't call panic but customize its exit code instead, so that's the reason why I also add this tip. Feel free to remove it if you think this is a bad design :)
=> feat: print backtrace when resulting errors

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.3.3 -> 1.4.0 (✓ API compatible changes)
<blockquote>
- print backtrace when resulting errors ([#215](https://github.com/Boshen/cargo-shear/pull/215))
- *(deps)* lock file maintenance rust crates ([#221](https://github.com/Boshen/cargo-shear/pull/221))
- *(deps)* update taiki-e/install-action action to v2.56.13 ([#220](https://github.com/Boshen/cargo-shear/pull/220))
- *(deps)* lock file maintenance ([#218](https://github.com/Boshen/cargo-shear/pull/218))
- *(deps)* update github-actions ([#217](https://github.com/Boshen/cargo-shear/pull/217))
</blockquote>
</p></details>
---
=> chore: release v1.4.0

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.4.0 -> 1.4.1 (✓ API compatible changes)
<blockquote>
- *(release)* enable trusted publishing
- *(deps)* lock file maintenance rust crates ([#226](https://github.com/Boshen/cargo-shear/pull/226))
- *(deps)* update github-actions ([#225](https://github.com/Boshen/cargo-shear/pull/225))
- *(deps)* lock file maintenance rust crates ([#223](https://github.com/Boshen/cargo-shear/pull/223))
- *(deps)* update github-actions ([#222](https://github.com/Boshen/cargo-shear/pull/222))
</blockquote>
</p></details>
---
=> chore: release v1.4.1

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.4.1 -> 1.5.0 (✓ API compatible changes)
<blockquote>
- improve logging for file read and parse ([#240](https://github.com/Boshen/cargo-shear/pull/240))
- *(deps)* lock file maintenance rust crates ([#239](https://github.com/Boshen/cargo-shear/pull/239))
- *(deps)* lock file maintenance rust crates ([#238](https://github.com/Boshen/cargo-shear/pull/238))
- *(deps)* update github-actions ([#237](https://github.com/Boshen/cargo-shear/pull/237))
- *(deps)* update crate-ci/typos action to v1.35.3 ([#235](https://github.com/Boshen/cargo-shear/pull/235))
- *(deps)* update crate-ci/typos action to v1.35.2 ([#234](https://github.com/Boshen/cargo-shear/pull/234))
- *(deps)* update dependency rust to v1.89.0 …
=> chore: release v1.5.0

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-shear`: 1.5.1 -> 1.5.2 (✓ API compatible changes)
<blockquote>
- optimize collect_tokens by replacing regex with string operations and iterators ([#274](https://github.com/Boshen/cargo-shear/pull/274))
- use rustc-hash for better performance ([#273](https://github.com/Boshen/cargo-shear/pull/273))
- add CLAUDE.md
- modularize codebase for better extensibility ([#271](https://github.com/Boshen/cargo-shear/pull/271))
- *(deps)* lock file maintenance rust crates ([#270](https://github.com/Boshen/cargo-shear/pull/270))
- *(deps)* update taiki-e/install-action action to v2.62.0 ([#269](https://github.com/Boshen/cargo-shear/pull/269))
- *(deps)* update dependency rust to v1.90.0 …
=> chore: release v1.5.2
